# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6afed4dfcc9b7f974a0f411d21e2b0bad43ebb7bb733e1936312bdd09466929b034d53c227eb270622dcc5282a4490faf6d3126966a030777e819a15919336ce

test:
  secret_key_base: 27d4429eb6cf74f9825bafb7c9602db8293b4db1f4fa9c3417cfaa14ebb6254df03888ad2bd174d6428c5362ffea67035e39b0b5a5e66be82adf2f079e32670e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
